// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
    `unsafe`
)

//go:nosplit
//go:noescape
//goland:noinspection ALL
func ___asm2asm_compiled_code__DO_NOT_CALL_THIS_SYMBOL___()

var (
    _func__base        = ___asm2asm_compiled_code__DO_NOT_CALL_THIS_SYMBOL___
    _subr__charAt      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 224
    _subr__f64toa      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 960
    _subr__i64toa      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 4017
    _subr__lspace      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 454
    _subr__lzero       = **(**uintptr)(unsafe.Pointer(&_func__base)) + 0
    _subr__quote       = **(**uintptr)(unsafe.Pointer(&_func__base)) + 5430
    _subr__skip_array  = **(**uintptr)(unsafe.Pointer(&_func__base)) + 21678
    _subr__skip_object = **(**uintptr)(unsafe.Pointer(&_func__base)) + 21713
    _subr__skip_one    = **(**uintptr)(unsafe.Pointer(&_func__base)) + 18811
    _subr__u64toa      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 4110
    _subr__unquote     = **(**uintptr)(unsafe.Pointer(&_func__base)) + 7227
    _subr__value       = **(**uintptr)(unsafe.Pointer(&_func__base)) + 14621
    _subr__vnumber     = **(**uintptr)(unsafe.Pointer(&_func__base)) + 17499
    _subr__vsigned     = **(**uintptr)(unsafe.Pointer(&_func__base)) + 18283
    _subr__vstring     = **(**uintptr)(unsafe.Pointer(&_func__base)) + 16362
    _subr__vunsigned   = **(**uintptr)(unsafe.Pointer(&_func__base)) + 18542
)

var (
    _ = _subr__charAt
    _ = _subr__f64toa
    _ = _subr__i64toa
    _ = _subr__lspace
    _ = _subr__lzero
    _ = _subr__quote
    _ = _subr__skip_array
    _ = _subr__skip_object
    _ = _subr__skip_one
    _ = _subr__u64toa
    _ = _subr__unquote
    _ = _subr__value
    _ = _subr__vnumber
    _ = _subr__vsigned
    _ = _subr__vstring
    _ = _subr__vunsigned
)
